//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phaola_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dados
    {
        public string Id { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<double> MatGorda { get; set; }
        public Nullable<double> Densidade { get; set; }
        public Nullable<double> Acidez { get; set; }
        public Nullable<double> Lactose { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> ESD { get; set; }
        public Nullable<double> EST { get; set; }
        public Nullable<double> Crioscopia { get; set; }
        public Nullable<double> Proteinas { get; set; }
        public Nullable<double> CCS { get; set; }
        public Nullable<double> CTB { get; set; }
        public Nullable<double> SolidosTotais { get; set; }
    }
}
